# @format

language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm run coveralls
    - stage: release
      node_js: lts/*
      script: npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release
