# @format

language: node_js
node_js:
  - 12

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      script: npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
          - npm publish
      deploy:
        provider: npm
        email: "zooka8548@gmail.com"
        api_key: "92d48112-cfea-489f-97b2-08d9075f666c"
